# Generated by Django 2.2.6 on 2019-11-11 01:25

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('horario', models.CharField(choices=[('sh', 'Abierto según horario'), ('24hs', 'Abierto las 24hs')], max_length=4)),
                ('delivery', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_locales')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='fotos_rubros')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.CharField(choices=[('co', 'CONSULTAR OFERTAS'), ('po', 'PUBLICAR OFERTAS')], max_length=2)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios')),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='app_ofertas.Local')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='app_ofertas.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='fotos_publicaciones')),
                ('precio_regular', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publi', models.DateTimeField(auto_now_add=True)),
                ('activada', models.BooleanField(default=True)),
                ('tiempo_publi', models.IntegerField(default=1440)),
                ('cant_visitas', models.IntegerField(default=0)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app_ofertas.Local')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app_ofertas.Rubro')),
            ],
            options={
                'ordering': ['fecha_publi'],
            },
        ),
        migrations.CreateModel(
            name='LocalMedioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_de_pago', to='app_ofertas.Local')),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ofertas.MedioDePago')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='app_ofertas.Localidad'),
        ),
        migrations.AddField(
            model_name='local',
            name='metodo_pago',
            field=models.ManyToManyField(through='app_ofertas.LocalMedioDePago', to='app_ofertas.MedioDePago'),
        ),
        migrations.AddField(
            model_name='local',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses', to='app_ofertas.Rubro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses', to='app_ofertas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=11)),
                ('hora_d1', models.CharField(max_length=5)),
                ('hora_h1', models.CharField(max_length=5)),
                ('hora_d2', models.CharField(blank=True, max_length=5, null=True)),
                ('hora_h2', models.CharField(blank=True, max_length=5, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='app_ofertas.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='app_ofertas.Local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='app_ofertas.Usuario')),
            ],
        ),
    ]
